logging:
  level:
    de:
      mmenze: DEBUG

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 2
      max-lifetime: 1200000
  liquibase:
    contexts: prod
    change-log: classpath:db/master.xml
  thymeleaf:
    cache: true

application:
  corona:
    johns-hopkins:
      csv-base-url: "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/"
    zeit:
      germany-url: "https://interactive.zeit.de/cronjobs/2020/corona/germany.json"
